name: Linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: feronatech/shared-workflows/.github/workflows/go-lint.yml@main
