name: Release
on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  version:
    runs-on: ubuntu-slim
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get Version
        id: get_version
        uses: feronatech/shared-workflows/.github/actions/get-version-from-tag@main
  release:
    uses: feronatech/shared-workflows/.github/workflows/go-lib-release.yml@main
    needs: version
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      wait-for-checks: "cve.yml,lint.yml,test.yml"
      release-body: |
        **Installation:**
        ```bash
        go get github.com/feronatech/go-aws-monitoring@v${{ needs.version.outputs.version }}
        ```
        **Usage:**
        ```go
        import (
            "context"
            "github.com/feronatech/go-aws-monitoring/monitoring"
            "github.com/feronatech/go-aws-monitoring/monitoring/pushgateway"
        )

        monitor, err := monitoring.SetupMonitoring(context.Background(), monitoring.MonitoringOptions{
            Region:      "us-east-1",
            Env:         "production",
            Application: "my-app",
            Transport:   pushgateway.NewTransport("http://pushgateway.example.com:9091", "", ""),
        })
        ```
